//
//  placeholderExtension.swift
//  Lingo Widget
//
//  Created by Oguz Doruk on 16.12.2024.
//


extension Word {
    static let placeholder: Word = {
        return Word(
            id: "hello",
            translations: [
                "en": Translation(
                    text: "hello",
                    exampleSentence: "Hello, how are you?",
                    romanized: nil,
                    romanizedExample: nil,
                    pronunciations: [
                        "tr": "he·lo",
                        "en": "he·loh",
                        "es": "je·lou",
                        "id": "he·lo",
                        "fr": "e·lo",
                        "it": "el·lo",
                        "pt": "e·lo",
                        "zh": "hei·lou",
                        "ru": "хе·лоу",
                        "ja": "he·ro",
                        "hi": "he·lo",
                        "fil": "he·lo",
                        "th": "เฮล·โล",
                        "ko": "헬·로",
                        "nl": "he·lo",
                        "sv": "he·lo",
                        "pl": "he·lou",
                        "el": "χέ·λοου",
                        "de": "he·lo"
                    ]
                ),
                "tr": Translation(
                    text: "merhaba",
                    exampleSentence: "Merhaba, nasılsın?",
                    romanized: nil,
                    romanizedExample: nil,
                    pronunciations: [
                        "tr": "mer·ha·ba",
                        "en": "mare·ha·bah",
                        "es": "mer·ja·ba",
                        "id": "mer·ha·ba",
                        "fr": "mer·a·ba",
                        "it": "mer·ha·ba",
                        "pt": "mer·ha·ba",
                        "zh": "梅尔哈巴",
                        "ru": "мер·ха·ба",
                        "ja": "メル·ハ·バ",
                        "hi": "मेर·ह·बा",
                        "fil": "mer·ha·ba",
                        "th": "เมร์·ฮา·บา",
                        "ko": "메르·하·바",
                        "nl": "mer·ha·ba",
                        "sv": "mer·ha·ba",
                        "pl": "mer·ha·ba",
                        "el": "μερ·χα·μπα",
                        "de": "mer·ha·ba"
                    ]
                ),
                "es": Translation(
                    text: "hola",
                    exampleSentence: "¡Hola! ¿Cómo estás?",
                    romanized: nil,
                    romanizedExample: nil,
                    pronunciations: [
                        "tr": "o·la",
                        "en": "oh·la",
                        "es": "o·la",
                        "id": "ho·la",
                        "fr": "o·la",
                        "it": "o·la",
                        "pt": "o·la",
                        "zh": "奥·拉",
                        "ru": "о·ла",
                        "ja": "オ·ラ",
                        "hi": "ओ·ला",
                        "fil": "o·la",
                        "th": "โอ·ลา",
                        "ko": "올·라",
                        "nl": "o·la",
                        "sv": "o·la",
                        "pl": "o·la",
                        "el": "ό·λα",
                        "de": "o·la"
                    ]
                ),
                "id": Translation(
                    text: "halo",
                    exampleSentence: "Halo, apa kabar?",
                    romanized: nil,
                    romanizedExample: nil,
                    pronunciations: [
                        "tr": "ha·lo",
                        "en": "hah·lo",
                        "es": "ha·lo",
                        "id": "ha·lo",
                        "fr": "a·lo",
                        "it": "ha·lo",
                        "pt": "ha·lo",
                        "zh": "哈·洛",
                        "ru": "ха·ло",
                        "ja": "ハ·ロ",
                        "hi": "हा·लो",
                        "fil": "ha·lo",
                        "th": "ฮา·โล",
                        "ko": "하·로",
                        "nl": "ha·lo",
                        "sv": "ha·lo",
                        "pl": "ha·lo",
                        "el": "χά·λο",
                        "de": "ha·lo"
                    ]
                ),
                "fr": Translation(
                    text: "bonjour",
                    exampleSentence: "Bonjour, comment allez-vous?",
                    romanized: nil,
                    romanizedExample: nil,
                    pronunciations: [
                        "tr": "bon·jur",
                        "en": "bohn·zhoor",
                        "es": "bon·yur",
                        "id": "bon·jur",
                        "fr": "bon·jour",
                        "it": "bon·giur",
                        "pt": "bon·jur",
                        "zh": "邦·茹尔",
                        "ru": "бон·жур",
                        "ja": "ボン·ジュー",
                        "hi": "बों·जूर",
                        "fil": "bon·jur",
                        "th": "บอง·จูร์",
                        "ko": "봉·주르",
                        "nl": "bon·zjur",
                        "sv": "bong·sjur",
                        "pl": "bą·żur",
                        "el": "μπον·ζούρ",
                        "de": "bon·schur"
                    ]
                ),
                "it": Translation(
                    text: "ciao",
                    exampleSentence: "Ciao, come stai?",
                    romanized: nil,
                    romanizedExample: nil,
                    pronunciations: [
                        "tr": "çav",
                        "en": "chow",
                        "es": "chao",
                        "id": "cao",
                        "fr": "tchao",
                        "it": "ciao",
                        "pt": "tchau",
                        "zh": "恰·奥",
                        "ru": "чао",
                        "ja": "チャ·オ",
                        "hi": "चाओ",
                        "fil": "chaw",
                        "th": "เชา",
                        "ko": "차·오",
                        "nl": "tsjau",
                        "sv": "tjao",
                        "pl": "ciao",
                        "el": "τσάο",
                        "de": "tschau"
                    ]
                ),
                "pt": Translation(
                    text: "olá",
                    exampleSentence: "Olá, como está?",
                    romanized: nil,
                    romanizedExample: nil,
                    pronunciations: [
                        "tr": "o·la",
                        "en": "oh·lah",
                        "es": "o·la",
                        "id": "o·la",
                        "fr": "o·la",
                        "it": "o·la",
                        "pt": "o·lá",
                        "zh": "奥·拉",
                        "ru": "о·ла",
                        "ja": "オ·ラ",
                        "hi": "ओ·ला",
                        "fil": "o·la",
                        "th": "โอ·ลา",
                        "ko": "올·라",
                        "nl": "o·la",
                        "sv": "o·la",
                        "pl": "o·la",
                        "el": "ό·λα",
                        "de": "o·la"
                    ]
                ),
                "zh": Translation(
                    text: "你好",
                    exampleSentence: "你好，你好吗？",
                    romanized: "nǐ hǎo",
                    romanizedExample: "nǐ hǎo, nǐ hǎo ma?",
                    pronunciations: [
                        "tr": "ni·hav",
                        "en": "nee·how",
                        "es": "ni·jao",
                        "id": "ni·hao",
                        "fr": "ni·hao",
                        "it": "ni·hao",
                        "pt": "ni·hao",
                        "zh": "你·好",
                        "ru": "ни·хао",
                        "ja": "ニー·ハオ",
                        "hi": "नी·हाओ",
                        "fil": "ni·hao",
                        "th": "หนี·ห่าว",
                        "ko": "니·하오",
                        "nl": "nie·hau",
                        "sv": "ni·hao",
                        "pl": "ni·hao",
                        "el": "νι·χάο",
                        "de": "ni·hao"
                    ]
                ),
                "ru": Translation(
                    text: "привет",
                    exampleSentence: "Привет, как дела?",
                    romanized: "privet",
                    romanizedExample: "Privet, kak dela?",
                    pronunciations: [
                        "tr": "pri·yet",
                        "en": "pree·vyet",
                        "es": "pri·viet",
                        "id": "pri·vyet",
                        "fr": "pri·viet",
                        "it": "pri·vyet",
                        "pt": "pri·vyet",
                        "zh": "普里维叶特",
                        "ru": "при·вет",
                        "ja": "プリ·ビェット",
                        "hi": "प्री·व्येत",
                        "fil": "pri·vyet",
                        "th": "พรี·เวียต",
                        "ko": "프리·벳",
                        "nl": "pri·vjet",
                        "sv": "pri·vjet",
                        "pl": "pri·wiet",
                        "el": "πρι·βιέτ",
                        "de": "pri·wjet"
                    ]
                ),
                "ja": Translation(
                    text: "こんにちは",
                    exampleSentence: "こんにちは、お元気ですか?",
                    romanized: "konnichiwa",
                    romanizedExample: "Konnichiwa, ogenkidesuka?",
                    pronunciations: [
                        "tr": "kon·ni·çi·va",
                        "en": "koh·nee·chee·wah",
                        "es": "kon·ni·chi·wa",
                        "id": "kon·ni·chi·wa",
                        "fr": "kon·ni·tchi·wa",
                        "it": "kon·ni·ci·wa",
                        "pt": "kon·ni·chi·wa",
                        "zh": "空你几哇",
                        "ru": "кон·ни·чи·ва",
                        "ja": "こん·に·ち·は",
                        "hi": "कोन्नी·ची·वा",
                        "fil": "kon·ni·chi·wa",
                        "th": "คน·นิ·ชิ·วะ",
                        "ko": "콘·니·치·와",
                        "nl": "kon·ni·tsji·wa",
                        "sv": "kon·ni·tji·wa",
                        "pl": "kon·ni·czi·wa",
                        "el": "κον·νί·τσι·ουα",
                        "de": "kon·ni·tschi·wa"
                    ]
                ),
                "hi": Translation(
                    text: "नमस्ते",
                    exampleSentence: "नमस्ते, कैसे हैं आप?",
                    romanized: "namaste",
                    romanizedExample: "Namaste, kaise hain aap?",
                    pronunciations: [
                        "tr": "na·mas·te",
                        "en": "nuh·muh·stay",
                        "es": "na·mas·te",
                        "id": "na·mas·te",
                        "fr": "na·mas·te",
                        "it": "na·mas·te",
                        "pt": "na·mas·te",
                        "zh": "纳马斯特",
                        "ru": "на·ма·сте",
                        "ja": "ナマス·テー",
                        "hi": "न·म·स्ते",
                        "fil": "na·ma·ste",
                        "th": "นะ·มัส·เต",
                        "ko": "나마스·테",
                        "nl": "na·ma·ste",
                        "sv": "na·ma·ste",
                        "pl": "na·ma·ste",
                        "el": "να·μά·στε",
                        "de": "na·ma·ste"
                    ]
                ),
                "fil": Translation(
                    text: "kamusta",
                    exampleSentence: "Kamusta, kumusta ka?",
                    romanized: nil,
                    romanizedExample: nil,
                    pronunciations: [
                        "tr": "ka·mus·ta",
                        "en": "kuh·moo·stah",
                        "es": "ka·mus·ta",
                        "id": "ka·mus·ta",
                        "fr": "ka·mous·ta",
                        "it": "ka·mu·sta",
                        "pt": "ka·mu·sta",
                        "zh": "卡木斯塔",
                        "ru": "ка·му·ста",
                        "ja": "カ·ム·スタ",
                        "hi": "क·मु·स्ता",
                        "fil": "ka·mus·ta",
                        "th": "คา·มุส·ตา",
                        "ko": "카·무·스타",
                        "nl": "ka·moe·sta",
                        "sv": "ka·mu·sta",
                        "pl": "ka·mu·sta",
                        "el": "κα·μού·στα",
                        "de": "ka·mu·sta"
                    ]
                ),
                "th": Translation( // Önceki kodun devamı
                    text: "สวัสดี",
                    exampleSentence: "สวัสดี คุณสบายดีไหม?",
                    romanized: "sawadee",
                    romanizedExample: "Sawadee, khun sabai dee mai?",
                    pronunciations: [
                        "tr": "sa·va·di",
                        "en": "sah·wah·dee",
                        "es": "sa·wa·di",
                        "id": "sa·wa·di",
                        "fr": "sa·wa·di",
                        "it": "sa·wa·di",
                        "pt": "sa·wa·di",
                        "zh": "萨瓦迪",
                        "ru": "са·ва·ди",
                        "ja": "サワ·ディー",
                        "hi": "सवा·डी",
                        "fil": "sa·wa·di",
                        "th": "ส·วัส·ดี",
                        "ko": "사와·디",
                        "nl": "sa·wa·di",
                        "sv": "sa·wa·di",
                        "pl": "sa·wa·di",
                        "el": "σα·βά·ντι",
                        "de": "sa·wa·di"
                    ]
                                 ),
                "ko": Translation(
                    text: "안녕하세요",
                    exampleSentence: "안녕하세요, 어떻게 지내세요?",
                    romanized: "annyeonghaseyo",
                    romanizedExample: "Annyeonghaseyo, eotteoke jinaeseyo?",
                    pronunciations: [
                        "tr": "an·yong·ha·se·yo",
                        "en": "ahn·nyong·hah·say·yo",
                        "es": "an·yong·ja·se·yo",
                        "id": "an·nyong·ha·se·yo",
                        "fr": "an·niong·ha·sé·yo",
                        "it": "an·niong·ha·se·io",
                        "pt": "an·nyong·ha·se·yo",
                        "zh": "安·永·哈·谢·哟",
                        "ru": "ан·нён·ха·се·ё",
                        "ja": "アン·ニョン·ハ·セ·ヨ",
                        "hi": "अन्योंग·हा·से·यो",
                        "fil": "an·nyong·ha·se·yo",
                        "th": "อัน·นยอง·ฮา·เซ·โย",
                        "ko": "안·녕·하·세·요",
                        "nl": "an·njong·ha·se·jo",
                        "sv": "an·nyong·ha·se·yo",
                        "pl": "an·niong·ha·se·jo",
                        "el": "αν·νιονγκ·χα·σε·γιο",
                        "de": "an·njong·ha·se·jo"
                    ]
                ),
                "nl": Translation(
                    text: "hallo",
                    exampleSentence: "Hallo, hoe gaat het?",
                    romanized: nil,
                    romanizedExample: nil,
                    pronunciations: [
                        "tr": "ha·lo",
                        "en": "hah·low",
                        "es": "ja·lo",
                        "id": "ha·lo",
                        "fr": "ha·lo",
                        "it": "ha·lo",
                        "pt": "ha·lo",
                        "zh": "哈·洛",
                        "ru": "ха·ло",
                        "ja": "ハ·ロー",
                        "hi": "हॅ·लो",
                        "fil": "ha·lo",
                        "th": "ฮัล·โล",
                        "ko": "할·로",
                        "nl": "hal·lo",
                        "sv": "hal·lo",
                        "pl": "ha·lo",
                        "el": "χά·λο",
                        "de": "hal·lo"
                    ]
                ),
                "sv": Translation(
                    text: "hej",
                    exampleSentence: "Hej, hur mår du?",
                    romanized: nil,
                    romanizedExample: nil,
                    pronunciations: [
                        "tr": "hey",
                        "en": "hey",
                        "es": "jey",
                        "id": "hey",
                        "fr": "hey",
                        "it": "hey",
                        "pt": "hey",
                        "zh": "黑伊",
                        "ru": "хей",
                        "ja": "ヘイ",
                        "hi": "हेज",
                        "fil": "hey",
                        "th": "เฮย",
                        "ko": "헤이",
                        "nl": "hej",
                        "sv": "hej",
                        "pl": "hej",
                        "el": "χέι",
                        "de": "hej"
                    ]
                ),
                "pl": Translation(
                    text: "cześć",
                    exampleSentence: "Cześć, jak się masz?",
                    romanized: nil,
                    romanizedExample: nil,
                    pronunciations: [
                        "tr": "çeşç",
                        "en": "cheshch",
                        "es": "chest",
                        "id": "cheshch",
                        "fr": "tchecht",
                        "it": "cesc",
                        "pt": "tcheshch",
                        "zh": "切什奇",
                        "ru": "чешч",
                        "ja": "チェシチ",
                        "hi": "चेश्च",
                        "fil": "cheshch",
                        "th": "เชช",
                        "ko": "체시치",
                        "nl": "tsjeshtsj",
                        "sv": "tjeshch",
                        "pl": "cześć",
                        "el": "τσεστς",
                        "de": "tscheschtsch"
                    ]
                ),
                "el": Translation(
                    text: "γεια",
                    exampleSentence: "Γεια, πώς είσαι;",
                    romanized: "geia",
                    romanizedExample: "Geia, pos eisai?",
                    pronunciations: [
                        "tr": "ya",
                        "en": "yah",
                        "es": "ya",
                        "id": "ya",
                        "fr": "ya",
                        "it": "ya",
                        "pt": "ya",
                        "zh": "亚",
                        "ru": "йя",
                        "ja": "ヤ",
                        "hi": "या",
                        "fil": "ya",
                        "th": "ยา",
                        "ko": "야",
                        "nl": "ja",
                        "sv": "ja",
                        "pl": "ja",
                        "el": "για",
                        "de": "ja"
                    ]
                ),
                "de": Translation(
                    text: "hallo",
                    exampleSentence: "Hallo, wie geht es dir?",
                    romanized: nil,
                    romanizedExample: nil,
                    pronunciations: [
                        "tr": "ha·lo",
                        "en": "hah·low",
                        "es": "ha·lo",
                        "id": "ha·lo",
                        "fr": "ha·lo",
                        "it": "ha·lo",
                        "pt": "ha·lo",
                        "zh": "哈·洛",
                        "ru": "ха·ло",
                        "ja": "ハ·ロー",
                        "hi": "हॅ·लो",
                        "fil": "ha·lo",
                        "th": "ฮัล·โล",
                        "ko": "할·로",
                        "nl": "hal·lo",
                        "sv": "hal·lo",
                        "pl": "ha·lo",
                        "el": "χά·λο",
                        "de": "hal·lo"
                    ]
                )
            ]
        )
    }()
}
